version: '3.1'
services:
  eureka-server:
    image: 'eureka-server'
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
  sleep-service:
    image: 'sleepservice:latest'
    build:
      context: .
      dockerfile: sleepservice/Dockerfile
    ports:
      - "8080:8080"
    container_name: sleepservice
    depends_on:
      - db
      - eureka-server
    links:
      - eureka-server
  auth-service:
    image: 'auth-server'
    build:
      context: .
      dockerfile: auth/Dockerfile
    ports:
        - "8082:8082"
    depends_on:
      - eureka-server
  statistic-service:
    image: 'statisic-service'
    build:
      context: .
      dockerfile: sleepstatistic/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - eureka-server
      - sleep-service
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  redis:
    image: redis:3.0.6
    ports:
      - "6379:6379"
