version: '3.1'
services:
  eureka-server:
    image: 'eureka-server'
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    ports:
      - "8761:8761"
  sleep-service:
    image: 'sleepservice:latest'
    build:
      context: .
      dockerfile: sleepservice/Dockerfile
    ports:
      - "8080:8080"
    container_name: sleepservice
    depends_on:
      - db
      - eureka-server
    links:
      - eureka-server
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  redis:
    image: redis:3.0.6
    ports:
      - "6378:6378"
