micronaut:
  application:
    name: auth
  server:
    port: 8082
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
netty:
  default:
    allocator:
      max-order: 3
eureka:
  instance:
    hostname: eureka-server
  client:
    registration:
      enabled: true
    defaultZone: http://eureka-server:8761/eureka