micronaut:
  server:
    port: 8081
  application:
    name: sleepstatistic
  http:
    services:
      sleepservice:
        urls:
          - http://sleep-service:8080
      auth:
        urls:
          - http://auth-service:8082
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  caches:
    my-cache:
      maximumSize: 20
netty:
  default:
    allocator:
      max-order: 3
redis:
  uri: redis://redis:6379
  io-thread-pool-size: 2
  computation-thread-pool-size: 2
eureka:
  client:
    registration:
      enabled: true
    defaultZone: http://eureka-server:8761/eureka
endpoints:
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
