micronaut:
  application:
    name: sleepservice
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://db:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '1234'
    dialect: POSTGRES
flyway:
  datasources:
    default:
      locations: classpath:db/migration
jpa:
  jpa:
    default:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          show_sql: true
eureka:
  instance:
    hostname: eureka-server
  client:
    registration:
      enabled: true
    defaultZone: http://eureka-server:8761/eureka